# Generated by Django 3.1.5 on 2021-01-22 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='birthday',
            field=models.DateField(),
        ),
    ]
