# Generated by Django 3.1.5 on 2021-01-25 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0004_auto_20210125_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=models.CharField(max_length=20),
        ),
    ]
