# Generated by Django 3.1.5 on 2021-01-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('birthdays', '0005_auto_20210125_0055'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='task_id',
            field=models.CharField(blank=True, default='<function uuid1 at 0x10f786320>', editable=False, max_length=50),
        ),
    ]
